### ISSUE TITLE
L2 Euclidean distance

### ISSUE THREAD

**Issue by Fyweven** [lanwuwei/Subword-PWIM#2]
About code 'simCube5 = torch.neg(F.pairwise_distance(simCube5_0, simCube5_1))'

Why neg?

**Comment by lanwuwei** [comment]
![image](https://user-images.githubusercontent.com/8783580/44380101-98de8580-a4c6-11e8-83a8-63867851b735.png)

**Comment by Fyweven** [comment]
Why pairwise_distanceneg
